export const ActionTypes = {
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SELECTED_PLAYLIST: "SELECTED_PLAYLIST",
  SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
  SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_EXPIRATION: "SET_EXPIRATION",
  SET_PLAYER: "SET_PLAYER",
  SET_PLAYING: "SET_PLAYING",
  SET_DEVICE: "SET_DEVICE"
};